---

dist: focal
language: python
python: "3.9"
os: linux
services:
  - docker
before_install:
  - echo '{"default-cgroupns-mode":"host"}' | sudo tee /etc/docker/daemon.json
  - sudo systemctl restart docker
install:
  - pip install pipenv
  - pipenv sync
env:
  jobs:
    - MOLECULE_DISTRO=debian:stretch-slim SCENARIO=cron-create-config
    - MOLECULE_DISTRO=debian:stretch-slim SCENARIO=cron-default
    - MOLECULE_DISTRO=debian:stretch-slim SCENARIO=cron-to-hourly
    - MOLECULE_DISTRO=debian:buster-slim SCENARIO=default
    - MOLECULE_DISTRO=debian:buster-slim SCENARIO=timer-create-config
    - MOLECULE_DISTRO=debian:buster-slim SCENARIO=timer-to-hourly
    - MOLECULE_DISTRO=debian:bullseye-slim SCENARIO=default
    - MOLECULE_DISTRO=debian:bullseye-slim SCENARIO=timer-create-config
    - MOLECULE_DISTRO=debian:bullseye-slim SCENARIO=timer-to-hourly
    - MOLECULE_DISTRO=debian:bookworm-slim SCENARIO=default
    - MOLECULE_DISTRO=debian:bookworm-slim SCENARIO=timer-create-config
    - MOLECULE_DISTRO=debian:bookworm-slim SCENARIO=timer-to-hourly
script:
  - pipenv run molecule test --scenario-name=${SCENARIO}

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
