---
dist: xenial
language: python
python: "3.7"
os: linux
services:
  - docker
install:
  - pip install pipenv
  - pipenv sync
env:
  jobs:
    - MOLECULE_DISTRO=debian:stretch-slim SCENARIO=changed-to-hourly
    - MOLECULE_DISTRO=debian:buster-slim SCENARIO=create-config
    - MOLECULE_DISTRO=debian:buster-slim SCENARIO=default
    - MOLECULE_DISTRO=debian:buster-slim SCENARIO=timer-to-hourly
script:
  - pipenv run molecule test --scenario-name=${SCENARIO}

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
