---

- name: LOGROTATE | Define systemd_path (Debian 10)
  set_fact:
    systemd_path: "{{ __systemd_path }}"
  when: systemd_path is not defined
  tags:
    - config
    - config-frequency

- name: LOGROTATE | Set facts
  set_fact:
    options: "{{ options|default([]) + item }}"
  with_items:
    - "{{ logrotate_config_file | json_query( '[*].options' ) }}"
  tags:
    - config
    - config-frequency

- name: LOGROTATE | Changing timer to hourly
  set_fact:
    timer_oncalendar: "{{ timer_oncalendar_hourly }}"
    timer_accuracysec: "{{ timer_accuracysec_hourly }}"
  when: "'hourly' in options"
  tags:
    - config
    - config-frequency

- name: LOGROTATE | Add timer
  template:
    src: "{{ logrotate_j2_timer }}"
    dest: "{{ systemd_path }}/{{ logrotate_timer }}"
    mode: 0644
  become: true
  tags:
    - config
    - config-frequency
