---

- name: LOGROTATE | Install
  import_tasks: install.yml
  tags:
    - install

- name: LOGROTATE | Configure
  import_tasks: config.yml
  tags:
    - config
  when: "logrotate_config_file is defined"

- name: LOGROTATE | Configure frequency
  include_tasks: "config-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  tags:
    - config
    - config-frequency
  when: "logrotate_config_file is defined"
