---

dependency:
  name: galaxy

driver:
  name: docker

lint: |
  yamllint .
  ansible-lint

platforms:
  - name: logrotate-cron-to-hourly
    groups:
      - logrotate
    image: ${MOLECULE_DISTRO:-debian:stretch-slim}
    privileged: false
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup'
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: cron-to-hourly

verifier:
  name: ansible
