---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint
platforms:
  - name: logrotate
    groups:
      - logrotate
    image: ${MOLECULE_DISTRO:-debian:buster-slim}
    privileged: true
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: timer-to-hourly

verifier:
  name: ansible
